CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  priority INT DEFAULT 0,
  completed BOOLEAN DEFAULT FALSE,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);